USE sakila;

-- 1. List the number of films per category. --

-- What tables and columns do I need?
-- film.film_id

-- film_category.film_id
-- film_category.category_id

-- category.category_id
-- category.name

-- The output columns I want to show --
SELECT
c.name,
COUNT(f.film_id) AS number_of_films
-- From which tables do I want to see this data
FROM category AS c
INNER JOIN film_category AS fc
-- On which common column
ON c.category_id = fc.category_id
-- Join again to the common column with film
JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.category_id, c.name;

-- 2. Retrieve the store ID, city, and country for each store.

-- store.store_id
-- store.address_id

-- address.address_id
-- address.city_id

-- city.city_id
-- city.city
-- city.country_id

-- country.country_id
-- country.county

-- The output columns I want to show --
-- store_id, city, country
SELECT
s.store_id,
c.city,
co.country
-- From which tables? First join store and address
FROM store AS s
INNER JOIN address AS a
-- On which common column
ON s.address_id = a.address_id
-- Join again to the next common column 
JOIN city AS c
ON a.city_id = c.city_id
-- Join again to the next common column 
JOIN country AS co
ON c.country_id = co.country_id
GROUP BY s.store_id, c.city, co.country;

-- 3. Calculate the total revenue generated by each store in dollars.

-- store.store_id
-- customer.store_id

-- customer.customer_id
-- payment.customer_id

-- payment.amount

-- The output columns I want to show --
-- store_id, total sum payment.amount
SELECT
s.store_id,
COUNT(p.amount) AS total_revenue
-- From which tables? First join store and customer
FROM store AS s
INNER JOIN customer AS c
-- On which common column
ON s.store_id = c.store_id
-- Join again to the next common column 
INNER JOIN payment AS p
ON c.customer_id = p.customer_id
-- Join again to the next common column 
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.

SELECT
c.name,
COUNT(f.film_id) AS number_of_films,
ROUND(AVG(f.length), 2) AS avg_duration
-- From which tables do I want to see this data
FROM category AS c
INNER JOIN film_category AS fc
-- On which common column
ON c.category_id = fc.category_id
-- Join again to the common column with film
JOIN film AS f
ON fc.film_id = f.film_id
GROUP BY c.name;

